Metrics/LineLength:
  Max: 120

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
      - 'vendor/*'
      - 'test/*'
      - 'doc/*'
      - 'lib/*'
      - 'features/**/*'
      - 'spec/**/*'
      - 'db/**/*'
      - 'config/**/*'
